name: marlin_auto_build

on:
  # trigger if we change a build
  push:
    paths:
      - 'builds/**'
  # trigger every Friday at 03AM
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch: # Put here!!  

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@v1.0.14
